// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentShop_API.Models.Data;

#nullable disable

namespace RentShop_API.Migrations
{
    [DbContext(typeof(RentDbContext))]
    [Migration("20231027175920_Initial-DataBase")]
    partial class InitialDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderShop", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdersId", "ShopsId");

                    b.HasIndex("ShopsId");

                    b.ToTable("OrderShop");
                });

            modelBuilder.Entity("OrderTransport", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdersId", "TransportsId");

                    b.HasIndex("TransportsId");

                    b.ToTable("OrderTransport");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7545ea0-d165-451b-891b-85c7ad800624"),
                            Name_Category = "Scooter"
                        },
                        new
                        {
                            Id = new Guid("f8262a42-2924-4bd0-a346-52de667eb1db"),
                            Name_Category = "Bike"
                        },
                        new
                        {
                            Id = new Guid("fd5121f7-75d6-4a56-b349-ea2f9f02f156"),
                            Name_Category = "Motorbike"
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.LogTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Results")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("LogTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bde66180-80a6-4945-aee0-3e6bb2f555fb"),
                            Results = true
                        },
                        new
                        {
                            Id = new Guid("9aafcda5-254a-4a83-835a-7c77713639ca"),
                            Results = true
                        },
                        new
                        {
                            Id = new Guid("e5c1dc46-bc95-4593-a8be-c5d104a1b841"),
                            Results = false
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb9276ec-07c3-444f-9089-deef9f880374"),
                            DateFrom = new DateTime(2023, 10, 27, 12, 55, 3, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3168),
                            Price = 55f
                        },
                        new
                        {
                            Id = new Guid("6a54f9de-b9c8-4008-87eb-f16c444cf728"),
                            DateFrom = new DateTime(2023, 10, 27, 12, 33, 13, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3186),
                            Price = 35f
                        },
                        new
                        {
                            Id = new Guid("869167b6-3754-4e3a-b137-a1bbbd779382"),
                            DateFrom = new DateTime(2023, 10, 27, 11, 25, 53, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3197),
                            Price = 155f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grand")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransportsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f82e1950-eade-4c4b-a843-d65c12c78525"),
                            Comment = "Bad",
                            CreatedAt = new DateTime(2023, 10, 27, 17, 59, 20, 151, DateTimeKind.Utc).AddTicks(3556),
                            Grand = 2
                        },
                        new
                        {
                            Id = new Guid("89a72202-1e5a-4abc-a7ba-eeec075b13e6"),
                            Comment = "Good",
                            CreatedAt = new DateTime(2023, 10, 27, 17, 59, 20, 151, DateTimeKind.Utc).AddTicks(3560),
                            Grand = 5
                        },
                        new
                        {
                            Id = new Guid("3fbbb959-ad20-48ff-9d0e-100213ea21bd"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2023, 10, 27, 17, 59, 20, 151, DateTimeKind.Utc).AddTicks(3566),
                            Grand = 4
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WorkTimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkTimeStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5be65bf-7141-4549-855b-d708e1eafa57"),
                            Address = "Street Victory 5",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("837d7d5b-78a3-4849-9299-266b2b9d8c7d"),
                            Address = "Street Livikovicha 15",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("4f9f82fe-bce2-4e12-b8bd-5f5d8d7f0665"),
                            Address = "Street Chresatic 55",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d145335e-e8ae-42c5-adda-53b331eac4aa"),
                            Date = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3508),
                            Sum = 125f
                        },
                        new
                        {
                            Id = new Guid("d56f0ac3-3f04-415d-8b84-3f108961dbc3"),
                            Date = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3514),
                            Sum = 25f
                        },
                        new
                        {
                            Id = new Guid("f0a1b6c7-f2fb-4db3-bc27-53aea9ed6a9b"),
                            Date = new DateTime(2023, 10, 27, 20, 59, 20, 151, DateTimeKind.Local).AddTicks(3518),
                            Sum = 120f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriceMinute")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e878d64-ade2-4d56-8cc1-4fecff92ef8a"),
                            ImgUrl = "http://...",
                            Mark = "Honda",
                            MaxSpeed = 35,
                            MaxWeight = 125,
                            Model = "V3",
                            PriceMinute = 3.5f
                        },
                        new
                        {
                            Id = new Guid("c2f5c199-097d-414a-b2fa-30c14b068f68"),
                            ImgUrl = "http://...",
                            Mark = "Tesla",
                            MaxSpeed = 45,
                            MaxWeight = 115,
                            Model = "Skod",
                            PriceMinute = 4.5f
                        },
                        new
                        {
                            Id = new Guid("925435be-2647-4a46-aeb1-d2dbceae5d76"),
                            ImgUrl = "http://...",
                            Mark = "Volva",
                            MaxSpeed = 30,
                            MaxWeight = 105,
                            Model = "Speed",
                            PriceMinute = 3f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.TransportAvailable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountTransport")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique()
                        .HasFilter("[ShopId] IS NOT NULL");

                    b.HasIndex("TransportId")
                        .IsUnique()
                        .HasFilter("[TransportId] IS NOT NULL");

                    b.ToTable("TransportAvailables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5d3cc5a-239d-4c3a-95e8-c72feccb287f"),
                            CountTransport = 15
                        },
                        new
                        {
                            Id = new Guid("da2bac03-3752-4fe9-8f5f-2cd4667ae7d2"),
                            CountTransport = 22
                        },
                        new
                        {
                            Id = new Guid("817de609-0ca0-4c15-88c4-d93c0e31f21f"),
                            CountTransport = 14
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("585a94d1-6e77-48e5-a5de-5d3fac9a15bb"),
                            BirthDate = new DateTime(2002, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khalin2002@gmail.com",
                            LastName = "Khalin",
                            Name = "Andrew",
                            Password = "10122002",
                            Phone = "+380737303288",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("d1e341d8-8a9a-408c-aeec-cdbdfea0332e"),
                            BirthDate = new DateTime(2001, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lebid@gmail.com",
                            LastName = "Lebid",
                            Name = "Vanya",
                            Password = "1920202",
                            Phone = "+380737303277",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("84b85103-b966-4e21-af94-5980b68d017a"),
                            BirthDate = new DateTime(2004, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shabaltas@gmail.com",
                            LastName = "Shabaltas",
                            Name = "Vlad",
                            Password = "648577",
                            Phone = "+380991833277",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("OrderShop", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentShop_API.Models.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderTransport", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentShop_API.Models.Entities.Transport", null)
                        .WithMany()
                        .HasForeignKey("TransportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.LogTransaction", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Transaction", "Transaction")
                        .WithOne("LogTransaction")
                        .HasForeignKey("RentShop_API.Models.Entities.LogTransaction", "TransactionId");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Rating", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Transport", "Transport")
                        .WithMany("Ratings")
                        .HasForeignKey("TransportId");

                    b.HasOne("RentShop_API.Models.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");

                    b.Navigation("Transport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("RentShop_API.Models.Entities.Transaction", "OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Category", "Category")
                        .WithMany("Transports")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.TransportAvailable", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Shop", "Shop")
                        .WithOne("TransportAvailable")
                        .HasForeignKey("RentShop_API.Models.Entities.TransportAvailable", "ShopId");

                    b.HasOne("RentShop_API.Models.Entities.Transport", "Transport")
                        .WithOne("TransportAvailable")
                        .HasForeignKey("RentShop_API.Models.Entities.TransportAvailable", "TransportId");

                    b.Navigation("Shop");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Category", b =>
                {
                    b.Navigation("Transports");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Shop", b =>
                {
                    b.Navigation("TransportAvailable");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.Navigation("LogTransaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("TransportAvailable");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
