// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentShop_API.Models.Data;

#nullable disable

namespace RentShop_API.Migrations
{
    [DbContext(typeof(RentDbContext))]
    partial class RentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderShop", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdersId", "ShopsId");

                    b.HasIndex("ShopsId");

                    b.ToTable("OrderShop");
                });

            modelBuilder.Entity("OrderTransport", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdersId", "TransportsId");

                    b.HasIndex("TransportsId");

                    b.ToTable("OrderTransport");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03b13ea3-1c23-48bc-9100-3f8447e729db"),
                            Name_Category = "Scooter"
                        },
                        new
                        {
                            Id = new Guid("b0a72c41-77ed-4a70-bf0d-3419d4df0f5c"),
                            Name_Category = "Bike"
                        },
                        new
                        {
                            Id = new Guid("979a107c-3aaf-4501-bb0f-eba5635a8081"),
                            Name_Category = "Motorbike"
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.LogTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Results")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("LogTransactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("846b5455-f0e2-4781-b0d5-b8c965bbaae1"),
                            Results = true
                        },
                        new
                        {
                            Id = new Guid("942352ea-532a-49ab-b82b-38c2ceb29a64"),
                            Results = true
                        },
                        new
                        {
                            Id = new Guid("b2dc3263-878a-4931-9c13-1918f7fb395b"),
                            Results = false
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae295cdb-37b4-4777-b694-664bfb02811b"),
                            DateFrom = new DateTime(2023, 10, 28, 12, 55, 3, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 28, 23, 46, 8, 584, DateTimeKind.Local).AddTicks(9946),
                            Price = 55f
                        },
                        new
                        {
                            Id = new Guid("c6daabeb-e90c-43b2-8a63-8308838335f4"),
                            DateFrom = new DateTime(2023, 10, 28, 12, 33, 13, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 28, 23, 46, 8, 584, DateTimeKind.Local).AddTicks(9961),
                            Price = 35f
                        },
                        new
                        {
                            Id = new Guid("17bddc87-3b52-4dea-9ced-3f2d1bf076bb"),
                            DateFrom = new DateTime(2023, 10, 28, 11, 25, 53, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 28, 23, 46, 8, 584, DateTimeKind.Local).AddTicks(9970),
                            Price = 155f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grand")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f2f78b-9d65-4875-8071-462bf4d09e36"),
                            Comment = "Bad",
                            CreatedAt = new DateTime(2023, 10, 28, 20, 46, 8, 585, DateTimeKind.Utc).AddTicks(212),
                            Grand = 2
                        },
                        new
                        {
                            Id = new Guid("d45f9e9e-35d3-4014-ab9a-153bfd5ff020"),
                            Comment = "Good",
                            CreatedAt = new DateTime(2023, 10, 28, 20, 46, 8, 585, DateTimeKind.Utc).AddTicks(215),
                            Grand = 5
                        },
                        new
                        {
                            Id = new Guid("b74f6e70-c8e1-43f2-a24b-85207bcfa853"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2023, 10, 28, 20, 46, 8, 585, DateTimeKind.Utc).AddTicks(218),
                            Grand = 4
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WorkTimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkTimeStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c247366-ff1a-4692-9015-412ff684de4d"),
                            Address = "Street Victory 5",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("170bfc2f-5b3d-41df-946e-2f84ac3d5316"),
                            Address = "Street Livikovicha 15",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("88ee7a78-94e1-4fcd-ae1d-432d554c42b0"),
                            Address = "Street Chresatic 55",
                            WorkTimeEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkTimeStart = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("972da729-279c-44ac-b683-fe8d1e412a27"),
                            Date = new DateTime(2023, 10, 28, 23, 46, 8, 585, DateTimeKind.Local).AddTicks(180),
                            Sum = 125f
                        },
                        new
                        {
                            Id = new Guid("0e5d35d5-559a-4b41-b2d2-5c275fec3970"),
                            Date = new DateTime(2023, 10, 28, 23, 46, 8, 585, DateTimeKind.Local).AddTicks(185),
                            Sum = 25f
                        },
                        new
                        {
                            Id = new Guid("efcb97e4-cd92-4613-b001-f1574dde3bb6"),
                            Date = new DateTime(2023, 10, 28, 23, 46, 8, 585, DateTimeKind.Local).AddTicks(189),
                            Sum = 120f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriceMinute")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddcd9353-b811-485a-b9a7-9e886a2d9871"),
                            ImgUrl = "http://...",
                            Mark = "Honda",
                            MaxSpeed = 35,
                            MaxWeight = 125,
                            Model = "V3",
                            PriceMinute = 3.5f
                        },
                        new
                        {
                            Id = new Guid("35705a50-fa2b-453a-833c-8dee0be68c53"),
                            ImgUrl = "http://...",
                            Mark = "Tesla",
                            MaxSpeed = 45,
                            MaxWeight = 115,
                            Model = "Skod",
                            PriceMinute = 4.5f
                        },
                        new
                        {
                            Id = new Guid("13e130ba-4766-4b3b-8aca-3a5ac268bea4"),
                            ImgUrl = "http://...",
                            Mark = "Volva",
                            MaxSpeed = 30,
                            MaxWeight = 105,
                            Model = "Speed",
                            PriceMinute = 3f
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.TransportAvailable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountTransport")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique()
                        .HasFilter("[ShopId] IS NOT NULL");

                    b.HasIndex("TransportId")
                        .IsUnique()
                        .HasFilter("[TransportId] IS NOT NULL");

                    b.ToTable("TransportAvailables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5da20ea5-1073-4693-a1aa-9305a39d04fa"),
                            CountTransport = 15
                        },
                        new
                        {
                            Id = new Guid("f22b84d2-f3b8-4948-8e7f-30cf11e7e73b"),
                            CountTransport = 22
                        },
                        new
                        {
                            Id = new Guid("dd31d57f-493d-43e6-ae27-882824a9c1bd"),
                            CountTransport = 14
                        });
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5af1e215-7722-4114-89ea-2b9e5aebac29"),
                            BirthDate = new DateTime(2002, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khalin2002@gmail.com",
                            LastName = "Khalin",
                            Name = "Andrew",
                            Password = "10122002",
                            Phone = "+380737303288",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("16d81047-a3a4-4e33-bf6f-f2f68a4d1bcb"),
                            BirthDate = new DateTime(2001, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lebid@gmail.com",
                            LastName = "Lebid",
                            Name = "Vanya",
                            Password = "1920202",
                            Phone = "+380737303277",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("4f990671-5a3f-4e77-a745-745446513434"),
                            BirthDate = new DateTime(2004, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shabaltas@gmail.com",
                            LastName = "Shabaltas",
                            Name = "Vlad",
                            Password = "648577",
                            Phone = "+380991833277",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("OrderShop", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentShop_API.Models.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderTransport", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentShop_API.Models.Entities.Transport", null)
                        .WithMany()
                        .HasForeignKey("TransportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.LogTransaction", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Transaction", "Transaction")
                        .WithOne("LogTransaction")
                        .HasForeignKey("RentShop_API.Models.Entities.LogTransaction", "TransactionId");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Rating", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Transport", "Transport")
                        .WithMany("Ratings")
                        .HasForeignKey("TransportId");

                    b.HasOne("RentShop_API.Models.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");

                    b.Navigation("Transport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("RentShop_API.Models.Entities.Transaction", "OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Category", "Category")
                        .WithMany("Transports")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.TransportAvailable", b =>
                {
                    b.HasOne("RentShop_API.Models.Entities.Shop", "Shop")
                        .WithOne("TransportAvailable")
                        .HasForeignKey("RentShop_API.Models.Entities.TransportAvailable", "ShopId");

                    b.HasOne("RentShop_API.Models.Entities.Transport", "Transport")
                        .WithOne("TransportAvailable")
                        .HasForeignKey("RentShop_API.Models.Entities.TransportAvailable", "TransportId");

                    b.Navigation("Shop");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Category", b =>
                {
                    b.Navigation("Transports");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Order", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Shop", b =>
                {
                    b.Navigation("TransportAvailable");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transaction", b =>
                {
                    b.Navigation("LogTransaction");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.Transport", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("TransportAvailable");
                });

            modelBuilder.Entity("RentShop_API.Models.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
