<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b06c8396-df78-4a43-b3cd-8856b0bb2bcd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Entities\Categories\**" />
    <Compile Remove="Models\Entities\LogTransaction\**" />
    <Compile Remove="Models\Entities\Order\**" />
    <Compile Remove="Models\Entities\Rating\**" />
    <Compile Remove="Models\Entities\Shops\**" />
    <Compile Remove="Models\Entities\Transaction\**" />
    <Compile Remove="Models\Entities\TransportAvailable\**" />
    <Compile Remove="Models\Entities\Transport\**" />
    <Compile Remove="Models\Entities\User\**" />
    <Content Remove="Models\Entities\Categories\**" />
    <Content Remove="Models\Entities\LogTransaction\**" />
    <Content Remove="Models\Entities\Order\**" />
    <Content Remove="Models\Entities\Rating\**" />
    <Content Remove="Models\Entities\Shops\**" />
    <Content Remove="Models\Entities\Transaction\**" />
    <Content Remove="Models\Entities\TransportAvailable\**" />
    <Content Remove="Models\Entities\Transport\**" />
    <Content Remove="Models\Entities\User\**" />
    <EmbeddedResource Remove="Models\Entities\Categories\**" />
    <EmbeddedResource Remove="Models\Entities\LogTransaction\**" />
    <EmbeddedResource Remove="Models\Entities\Order\**" />
    <EmbeddedResource Remove="Models\Entities\Rating\**" />
    <EmbeddedResource Remove="Models\Entities\Shops\**" />
    <EmbeddedResource Remove="Models\Entities\Transaction\**" />
    <EmbeddedResource Remove="Models\Entities\TransportAvailable\**" />
    <EmbeddedResource Remove="Models\Entities\Transport\**" />
    <EmbeddedResource Remove="Models\Entities\User\**" />
    <None Remove="Models\Entities\Categories\**" />
    <None Remove="Models\Entities\LogTransaction\**" />
    <None Remove="Models\Entities\Order\**" />
    <None Remove="Models\Entities\Rating\**" />
    <None Remove="Models\Entities\Shops\**" />
    <None Remove="Models\Entities\Transaction\**" />
    <None Remove="Models\Entities\TransportAvailable\**" />
    <None Remove="Models\Entities\Transport\**" />
    <None Remove="Models\Entities\User\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
